--[[ /ccagent/install.lua ------------------------------------------------
  First-run setup.

    ccagent/install                     -- local setup only
    ccagent/install <base-url>          -- pull the library down first
    ccagent/install --startup worker    -- and boot into worker mode

  "Local setup" means: make the directories, ask for the API key once, drop
  a /ccagent shim on the path so you can type `ccagent` from anywhere, and
  run a self-check that tells you what this machine can and cannot do.

  Downloading is boot.lua's job -- it owns manifest.txt, the fetch loop and
  the source configuration, so none of that is written down twice. Given a
  base url this script fetches boot.lua if it has to, then delegates. On a
  bare machine you would normally start from boot.lua instead:

      wget run <wherever-you-keep-it>/boot.lua

  <base-url> here is a plain directory holding the tree. A source that
  needs a token or a url template is boot.lua's business; run it directly.
--------------------------------------------------------------------------]]

local args = { ... }
local base, startupMode = nil, nil
for i = 1, #args do
  if args[i] == "--startup" then startupMode = args[i + 1]
  elseif args[i]:match("^https?://") then base = args[i]:gsub("/$", "") end
end

local function say(s) print(s) end

---------------------------------------------------------------- download --

if base then
  if not http then
    error("the http API is disabled in this world; copy the files in by hand", 0)
  end
  -- boot.lua does the pulling. Fetch it first if this machine only has
  -- install.lua (someone pasted it in by hand, say).
  local bootPath = "/ccagent/boot.lua"
  if not fs.exists(bootPath) then
    local url = base .. "/boot.lua"
    write("fetching boot.lua ... ")
    local res = http.get(url)
    if not res then
      print("FAILED")
      error("could not fetch " .. url, 0)
    end
    local data = res.readAll()
    res.close()
    if not fs.exists("/ccagent") then fs.makeDir("/ccagent") end
    local h = fs.open(bootPath, "w")
    h.write(data); h.close()
    print("ok")
  end
  if not shell then error("run this from the shell so it can call boot.lua", 0) end
  shell.run(bootPath, "--url", base, "--no-setup")
end

------------------------------------------------------------------ setup ---

for _, d in ipairs({ "/ccagent", "/ccagent/jobs", "/.ccagent" }) do
  if not fs.exists(d) then fs.makeDir(d) end
end

-- A shim so `ccagent` works from any directory. Generated, not yours to
-- edit: rewritten on every install so an old launcher cannot outlive the
-- modes it knows about.
do
  local h = fs.open("/ccagent.lua", "w")
  h.write([[
-- ccagent launcher -- generated by /ccagent/install.lua, edits are lost.
local mode = ...
local rest = { select(2, ...) }
local unpack = table.unpack or unpack   -- CC's Lua has only the global one
local map = {
  host   = "/ccagent/ui/host.lua",
  worker = "/ccagent/ui/worker.lua",
  solo   = "/ccagent/ui/controller.lua",
  update = "/ccagent/boot.lua",
}
if mode and map[mode] then
  shell.run(map[mode], unpack(rest))
else
  shell.run("/ccagent/ui/controller.lua", ...)
end
]])
  h.close()
  say("installed /ccagent.lua launcher")
end

-- API key.
local keyPath = "/.ccagent/key"
if not fs.exists(keyPath) then
  say("")
  say("Anthropic API key (from console.anthropic.com).")
  say("Stored in " .. keyPath .. " only. Leave blank to skip (worker-only machines")
  say("do not need one).")
  write("key> ")
  local key = read()
  if key and key:gsub("%s", "") ~= "" then
    local h = fs.open(keyPath, "w")
    h.write((key:gsub("^%s+", ""):gsub("%s+$", "")))
    h.close()
    say("saved")
  else
    say("skipped")
  end
end

if startupMode then
  local h = fs.open("/startup.lua", "w")
  h.write(('shell.run("/ccagent.lua", "%s")\n'):format(startupMode))
  h.close()
  say("startup set to " .. startupMode)
end

----------------------------------------------------------------- check ----

package.path = "/?.lua;/?/init.lua;" .. (package.path or "")
local ok, agent = pcall(require, "agent.init")
if not ok then
  say("")
  say("self-check FAILED: " .. tostring(agent))
  say("are all the files under /ccagent/ ?")
  return
end

agent.boot({ calibrate = false })
local registry = require("agent.registry")
local tokens = registry.manifestCost()

say("")
say("ccagent " .. agent.VERSION .. " ready")
say("  capabilities : " .. agent.caps.summary())
say("  api manifest : ~" .. tokens .. " tokens (cached after the first call)")
say("  http         : " .. (http and "available" or "DISABLED in this world"))
say("")
if agent.caps.has("turtle") then
  say("  run  ccagent          -- standalone (needs a key on this turtle)")
  say("  run  ccagent worker   -- join a host over rednet (no key needed)")
else
  say("  run  ccagent host     -- drive turtles over rednet from here")
end
if fs.exists("/.ccagent/source") then
  say("  run  ccagent update   -- re-pull the library from where it came from")
end
if not agent.caps.has("gps") then
  say("")
  say("  note: no GPS fix. Coordinates will be local to wherever the turtle")
  say("        booted. A GPS constellation makes them match the world's.")
end
