--[[ /ccagent/setup.lua --------------------------------------------------
  First-run setup.

    ccagent/setup                       -- local setup only
    ccagent/setup <base-url>            -- pull the library down first
    ccagent/setup --startup worker      -- and start in worker mode

  You do not normally run this. `install.lua` runs it for you once the
  files are down; it is separate so the download logic lives in exactly
  one place.

  "Local setup" means: make the directories, ask for the API key once, drop
  a /ccagent shim on the path so you can type `ccagent` from anywhere, and
  run a self-check that tells you what this machine can and cannot do.

  Downloading is install.lua's job -- it owns manifest.txt, the fetch loop
  and the source configuration, so none of that is written down twice.
  Given a base url this script fetches install.lua if it has to, then
  delegates. On a bare machine you start from install.lua instead:

      wget run <wherever-you-keep-it>/install.lua

  <base-url> here is a plain directory holding the tree. A source that
  needs a token or a url template is install.lua's business; run that.
--------------------------------------------------------------------------]]

local args = { ... }
local base, startupMode, resetKey = nil, nil, false
for i = 1, #args do
  if args[i] == "--startup" then startupMode = args[i + 1]
  elseif args[i] == "--key" then resetKey = true
  elseif args[i]:match("^https?://") then base = args[i]:gsub("/$", "") end
end

local function say(s) print(s) end

---------------------------------------------------------------- download --

if base then
  if not http then
    error("the http API is disabled in this world; copy the files in by hand", 0)
  end
  -- install.lua does the pulling. Fetch it first if this machine only has
  -- setup.lua (someone pasted it in by hand, say).
  local bootPath = "/ccagent/install.lua"
  if not fs.exists(bootPath) then
    local url = base .. "/install.lua"
    write("fetching install.lua ... ")
    local res = http.get(url)
    if not res then
      print("FAILED")
      error("could not fetch " .. url, 0)
    end
    local data = res.readAll()
    res.close()
    if not fs.exists("/ccagent") then fs.makeDir("/ccagent") end
    local h = fs.open(bootPath, "w")
    h.write(data); h.close()
    print("ok")
  end
  if not shell then error("run this from the shell so it can call install.lua", 0) end
  shell.run(bootPath, "--url", base, "--no-setup")
end

------------------------------------------------------------------ setup ---

for _, d in ipairs({ "/ccagent", "/ccagent/jobs", "/.ccagent" }) do
  if not fs.exists(d) then fs.makeDir(d) end
end

-- Refuse to half-install. Without a base url this script does local setup
-- only, so on a bare machine it used to write a launcher, then fail a
-- self-check with a Lua module error naming agent.init -- which tells you
-- nothing about the step you actually skipped. install.lua is the entry
-- point; this is what it runs afterwards.
if not base and not fs.exists("/ccagent/agent/init.lua") then
  say("ccagent: nothing to set up here.")
  say("")
  say("setup.lua is the second half of an")
  say("install. The library is not in")
  say("/ccagent yet, so run install.lua")
  say("first -- it fetches the files and")
  say("then runs this for you:")
  say("")
  say("  wget run <source>/install.lua \\")
  say("      <source>")
  return
end

-- The launcher. Run it as /ccagent (absolute) from anywhere, or as
-- `ccagent` from / -- the shell's path is ".:/rom/programs", so a program
-- at the root is only found when the root is the current directory.
-- Generated, not yours to edit: rewritten on every install so an old
-- launcher cannot outlive the modes it knows about.
do
  local h = fs.open("/ccagent.lua", "w")
  h.write([[
-- ccagent launcher -- generated by /ccagent/setup.lua, edits are lost.
local mode = ...
local rest = { select(2, ...) }
local unpack = table.unpack or unpack   -- CC's Lua has only the global one
local map = {
  host   = "/ccagent/ui/host.lua",
  worker = "/ccagent/ui/worker.lua",
  solo   = "/ccagent/ui/controller.lua",
  update = "/ccagent/install.lua",
}
if mode and map[mode] then
  shell.run(map[mode], unpack(rest))
else
  shell.run("/ccagent/ui/controller.lua", ...)
end
]])
  h.close()
  say("installed /ccagent.lua launcher")
end

-- API key. `ccagent/setup --key` re-asks when one is already stored.
local keyPath = "/.ccagent/key"
if resetKey or not fs.exists(keyPath) then
  say("")
  say("Anthropic API key.")
  say("console.anthropic.com")
  say("Kept in " .. keyPath .. " only.")
  say("Blank to skip; workers need none.")
  write("key> ")
  local key = read()
  key = key and (key:gsub("^%s+", ""):gsub("%s+$", "")) or ""
  if key ~= "" then
    local h = fs.open(keyPath, "w")
    h.write(key)
    h.close()
    -- A key mistyped into a 39-column terminal otherwise stays silent
    -- until the first request comes back 401, long after the typing.
    if not key:match("^sk%-ant%-") then
      say("saved, but it does not start")
      say("with sk-ant- . Re-run with:")
      say("  /ccagent/setup --key")
    elseif #key < 40 then
      say("saved, but it looks short at")
      say(#key .. " chars -- truncated?")
    else
      say("saved (" .. #key .. " chars)")
    end
  else
    say("skipped")
  end
end

if startupMode then
  local h = fs.open("/startup.lua", "w")
  h.write(('shell.run("/ccagent.lua", "%s")\n'):format(startupMode))
  h.close()
  say("startup set to " .. startupMode)
end

----------------------------------------------------------------- check ----

-- The tree lives at /ccagent (agent/lib.lua and claude/config.lua say so
-- too). CC also searches the running program's own directory, which is
-- why a wrong prefix here still works from /ccagent/setup.lua and
-- fails from /ccagent/ui/ one level down.
package.path = "/ccagent/?.lua;/ccagent/?/init.lua;" .. (package.path or "")
local ok, agent = pcall(require, "agent.init")
if not ok then
  say("")
  say("self-check FAILED:")
  say(tostring(agent))
  say("are all files under /ccagent ?")
  return
end

agent.boot({ calibrate = false })
local registry = require("agent.registry")
local tokens = registry.manifestCost()

-- Everything below is read on a turtle: 39 columns, 13 rows, no
-- scrollback. Absolute paths, because /ccagent.lua is only on the shell's
-- search path when the current directory happens to be / -- "ccagent" on
-- its own resolves from there and nowhere else.
say("")
say("ccagent " .. agent.VERSION .. " ready")
say("caps : " .. agent.caps.summary())
say("api  : ~" .. tokens .. " tokens cached")
say("http : " .. (http and "ok" or "DISABLED"))
say("")
if agent.caps.has("turtle") then
  say("/ccagent         standalone")
  say("/ccagent worker  join a host")
else
  say("/ccagent host    drive turtles")
end
if fs.exists("/.ccagent/source") then
  say("/ccagent update  re-pull")
end
if not agent.caps.has("gps") then
  say("")
  say("no GPS: positions are local to")
  say("where this machine booted.")
end
